services:
  - type: web
    name: caprae-lead-ranker
    env: python
    plan: free # Use the free instance type
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11 # Or your Python version
      - key: GOOGLE_API_KEY
        fromSecret: true # We will set this in the Render dashboard
      - key: GOOGLE_CSE_ID
        fromSecret: true # We will set this in the Render dashboard